# Generated by Django 5.1.5 on 2025-01-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_posts_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostsStat",
            fields=[
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="posts.posts",
                    ),
                ),
                ("total_likes", models.PositiveIntegerField()),
                ("total_commets", models.PositiveIntegerField()),
            ],
        ),
    ]
