# Generated by Django 5.1.5 on 2025-01-18 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_postsstat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postsstat",
            old_name="total_commets",
            new_name="total_comments",
        ),
        migrations.AlterField(
            model_name="postsstat",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="statistic",
                serialize=False,
                to="posts.posts",
            ),
        ),
    ]
