# Generated by Django 5.1.5 on 2025-01-19 05:11

import mini_post.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_total_commets_postsstat_total_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=mini_post.utils.get_fileupload_path
            ),
        ),
    ]
